# Generated by Django 6.0.3 on 2026-03-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_candidate_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "required_skills",
                    models.TextField(
                        help_text="Comma-separated skills (e.g. Python, SQL, React)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="match_score",
            field=models.FloatField(
                default=0.0, help_text="Skill match percentage with job posting"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="recruitment.jobposting",
            ),
        ),
    ]
