# Generated by Django 6.0.3 on 2026-03-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_jobposting_candidate_match_score_candidate_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "skills_required",
                    models.TextField(
                        help_text="Comma-separated skills (e.g. Python, SQL, React)"
                    ),
                ),
                (
                    "experience",
                    models.CharField(help_text="e.g. 2+ years", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="candidate",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="recruitment.job",
            ),
        ),
        migrations.DeleteModel(
            name="JobPosting",
        ),
    ]
