# Generated by Django 6.0.3 on 2026-03-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_job_alter_candidate_job_delete_jobposting"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_shortlisted",
            field=models.BooleanField(default=False),
        ),
    ]
